CREATE TABLE Users(id int AUTO_INCREMENT, email VARCHAR(255), username VARCHAR(255), password VARCHAR(255), PRIMARY KEY(id));

ALTER TABLE users ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP, ADD COLUMN isAdmin BOOLEAN DEFAULT FALSE;

CREATE TABLE Invites(code VARCHAR(255), createdBy INT, used BOOL, usedBy INT, PRIMARY KEY(code), FOREIGN KEY(createdBy) REFERENCES Users(id), FOREIGN KEY(usedBy) REFERENCES Users(id));


ALTER TABLE Users AUTO_INCREMENT = 1
